// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKjkTYgWDvoD-rEvlHwXU7LTaNXBkT7dk',
    appId: '1:183062557302:web:81eadd161220ccf66fe557',
    messagingSenderId: '183062557302',
    projectId: 'ramma-d8d30',
    authDomain: 'ramma-d8d30.firebaseapp.com',
    storageBucket: 'ramma-d8d30.firebasestorage.app',
    measurementId: 'G-3T47Z8DH4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4PUAXILEDOuAuFlqN-BO96hOxuVGA-CQ',
    appId: '1:183062557302:android:2eec5f38f1b430fd6fe557',
    messagingSenderId: '183062557302',
    projectId: 'ramma-d8d30',
    storageBucket: 'ramma-d8d30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALW2AfB66L39b_XCjBoxewr7aHv46tWho',
    appId: '1:183062557302:ios:364d1230ad1dce3a6fe557',
    messagingSenderId: '183062557302',
    projectId: 'ramma-d8d30',
    storageBucket: 'ramma-d8d30.firebasestorage.app',
    iosBundleId: 'com.example.rammaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALW2AfB66L39b_XCjBoxewr7aHv46tWho',
    appId: '1:183062557302:ios:364d1230ad1dce3a6fe557',
    messagingSenderId: '183062557302',
    projectId: 'ramma-d8d30',
    storageBucket: 'ramma-d8d30.firebasestorage.app',
    iosBundleId: 'com.example.rammaa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKjkTYgWDvoD-rEvlHwXU7LTaNXBkT7dk',
    appId: '1:183062557302:web:a9cffde6018b31756fe557',
    messagingSenderId: '183062557302',
    projectId: 'ramma-d8d30',
    authDomain: 'ramma-d8d30.firebaseapp.com',
    storageBucket: 'ramma-d8d30.firebasestorage.app',
    measurementId: 'G-DEXHWZLV2B',
  );
}
