class AppRoutes {
  static const splash = '/splash';
  static const welcome = '/welcome';
  static const language = '/language';
  static const intro = '/intro';
  static const login = '/login';
  static const signup = '/signup';
  static const otp = '/otp';
  static const roleSelection = '/role-selection';
  static const forgotPassword = '/forgot-password';
  static const patientDashboard = '/patient-dashboard';
  static const providerDashboard = '/provider-dashboard';
  static const homeDashboard      = '/home-dashboard';
  static const caregiverDashboard = '/caregiver-dashboard';
  static const providerList     = '/provider-list';   // ← NEW
  static const providerProfile  = '/provider-profile'; // ← for next screen
  static const bookAppointment  = '/book-appointment'; // ← for next screen
  static const caregiverList = '/caregiver-list';
  static const bookingSummary = '/booking-summary';
  static const payment = '/payment';
  static const bookingSuccess = '/booking-success';
  static const appointments = '/appointments';
  static const healthMonitor = '/health-monitor';
  static const chat = '/chat';
  static const profile = '/profile';
  static const booking = '/booking';
  static const healthAlert = '/health-alert';
  static const paymentSuccess = '/payment-success';
  static const invoice = '/invoice';
  static const transactionHistory = '/transaction-history';
  static const aiChat = '/ai-chat';
  static const notification = '/notification';
  static const providerEditProfile = '/provider-edit-profile';
  static const patientEditProfile = '/patient-edit-profile';
  static const providerPatientDetail = '/provider-patient-detail';
  static const providerEditPatient = '/provider-edit-patient';
  static const providerWithdraw = '/provider-withdraw';
  static const providerEarningsHistory = '/provider-earnings-history';
  static const caregiverMessages = '/caregiver-messages';
  static const caregiverEditProfile = '/caregiver-edit-profile';
  static const caregiverClientDetail = '/caregiver-client-detail';
  static const caregiverWithdraw = '/caregiver-withdraw';
  static const caregiverEarningsHistory = '/caregiver-earnings-history';
  static const videoCall = '/video-call';
  static const audioCall = '/audio-call';
  static const incomingCall = '/incoming-call';
  static const helpSupport = '/help-support';
  static const privacySecurity = '/privacy-security';
  static const settings = '/settings';
}